### ISSUE TITLE
Plugin properties instead of configuration section

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/java-common#59]
Where possible qa-parent should set plugin properties instead of using the configuration section to make it easier for projects to override.

For example, with the PMD plugin, qa-parent currently sets the verbose flag in the configuration section. This means projects need to override the plugin definition  instead of being able to just set the "pmd.verbose" property. In this case, qa-parent should be changed to set the "pmd.verbose" property.

**Comment by marksreeves** [comment]
@jonathanaustin is this issue still active? I thought you had undertaken this refactor of properties several months ago?

**Comment by jonathanaustin** [comment]
We did do the major refactor, but unfortunately some of the plugins (eg PMD) still have properties set in their configuration which do not allow projects to override them with by just setting a property, they need to include the plugin itself to override. Where possible we need to set the property instead of doing it in the configuration section.
